POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
    "email":"user001@email.com",
    "password":"Gymbro123"
}

###

POST http://localhost:8000/api/v1/auth/signup
Content-Type: application/json

{
    "email":"user005@email.com",
    "password":"Gymbro123",
    "firstName":"User",
    "lastName":"005"
}

###

POST http://localhost:8000/api/v1/auth/refresh_token
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImp0aSI6ImUxMjc2NzlkLTk5N2UtNGJjOS05NzJmLWIxZmM3YWIzMjliNyIsImlhdCI6MTY3OTQ4NzU4NiwiZXhwIjoxNjc5NTE2Mzg2fQ.EXwqm43VstwyO-i0h7bt8dINoQsJlqkVQj6DCQ8NJ6U"
}

###

POST http://localhost:8000/api/v1/auth/revoke_refresh_tokens
Content-Type: application/json

{
    "userId":"1"
}

###